language: ruby
cache: bundler
services:
  - postgresql
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle install --jobs=3 --retry=3 --deployment
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
